#!/bin/sh
set -e
if [ "$1" = "upgrade" ] || [ "$1" = "install" ]; then
    systemctl stop update-lug-sites.service || true
    systemctl stop update-lug-sites.timer  || true
    systemctl disable lug-sites-sync.service  || true
    systemctl disable lug-sites-sync.timer || true
fi
