#!/bin/sh
set -e
if [ "$1" = "remove" -o "$1" = "deconfigure" ]; then
    systemctl stop update-lug-sites.timer
    systemctl stop update-lug-sites.service
    systemctl disable update-lug-sites.timer
    systemctl disable update-lug-sites.service
fi
