#!/bin/sh
set -e
if [ "$1" = "configure" ] || [ "x$1" = "install" ]; then
    systemctl enable update-lug-sites.service
    systemctl enable update-lug-sites.timer
    systemctl start update-lug-sites.timer
    echo "Service enabled."
fi
