all:
	install -m 755 -T usr/bin/update-lug-sites /usr/bin/update-lug-sites
	install -m 644 -T lib/systemd/system/update-lug-sites.service /lib/systemd/system/update-lug-sites.service
	install -m 644 -T lib/systemd/system/update-lug-sites.timer /lib/systemd/system/update-lug-sites.timer
