all:

install:
	install -m 755 -T usr/bin/update-lug-sites $(DESTDIR)/usr/bin/update-lug-sites
	install -m 644 -T lib/systemd/system/update-lug-sites.service $(DESTDIR)/lib/systemd/system/update-lug-sites.service
	install -m 644 -T lib/systemd/system/update-lug-sites.timer $(DESTDIR)/lib/systemd/system/update-lug-sites.timer
